spring:
  autoconfigure:
    exclude: # 여기를 이렇게 재정의 함으로써 운영환경에서는 레디스가 다시 활성화 됩니다.
  data:
    redis:
      host: redis_1
      password: ${SPRING__DATA__REDIS__PASSWORD}
  datasource:
    url: jdbc:mysql://mysql_1:3306/${SPRING__DATASOURCE__URL___DB_NAME}
    username: lldjlocal
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
custom:
  site:
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
    name: p-14044-1
